### ISSUE TITLE
Research, setAccessble(true) headache on Java21

### ISSUE THREAD

**Issue by jflute** [lastaflute/lastaflute#83]
Japanese here:

LastaFluteをJava21で動かそうとすると、Java9のJigsawの影響とJavaa16からillegal-accessがデフォルトでstrictになったことによって、AopProxyがまともに動かない。

```
public void test_demo() throws Exception {
    Pointcut pointcut = new PointcutImpl(new String[] { "test_demo" });
    Aspect aspect = new AspectImpl(new SeaMethodInterceptor(), pointcut);
    AopProxy aopProxy = new AopProxy(getClass(), new Aspect[] { aspect });
    log(aopProxy);
...
```

```
...
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2f96847e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.lastaflute.di.core.aop.javassist.AbstractGenerator$2.run(AbstractGenerator.java:68)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.lastaflute.di.core.aop.javassist.AbstractGenerator.<clinit>(AbstractGenerator.java:62)
```

他にもjavaパッケージのクラスに対するsetAccessble(true)があるかもしれない。
javaコマンドのオプションで--add-opensオプションをつければ回避できるだけもだけど現実的な解決策ではない。

この辺りを検証していく。

**Comment by jflute** [comment]
Unsafeを使おうと思ったけど、そもそもUnsafeも素直に使えなくなっている模様。

ただ、GsonのUnsafeAllocatorがちょっと気になるので分析してみよう。
https://github.com/google/gson/blob/main/gson/src/main/java/com/google/gson/internal/UnsafeAllocator.java

**Comment by jflute** [comment]
GsonのUnsafeAllocatorは、Unsafeを使おうとしてるけど...
単に「コンストラクター実行せずにnewするためだけのクラス」っぽいので、
そのままこっちのやりたいことに使えるわけではなさそう。

```
UnsafeAllocator allocator = UnsafeAllocator.create();
log(allocator, allocator.getClass());
Sea sea = allocator.newInstance(Sea.class);
log(sea, sea.getClass());
sea.mystic();
```
public static class Sea {

    private final String hangar;

    public Sea() {
        System.out.println("@@@@@@@@@@@@@@@@@ :: constructor");
        hangar = "stage";
    }

    public void mystic() {
        System.out.println("@@@@@@@@@@@@@@@@@ :: mystic :: " + hangar);
    }
}
```

```
2024-06-17 17:20:42,708 [main] DEBUG (PlainTestCase@log():750) - com.google.gson.internal.UnsafeAllocator$1@2d0bfb24, class com.google.gson.internal.UnsafeAllocator$1
2024-06-17 17:20:42,709 [main] DEBUG (PlainTestCase@log():750) - org.docksidestage.unit.DemoTest$Sea@38499e48, class org.docksidestage.unit.DemoTest$Sea
@@@@@@@@@@@@@@@@@ :: mystic :: null
```

本当にコンストラクター実行されないし、finalの変数がnullのまんまだしと Unsafe だわーって感じ(^^。
すごいね。

中では、Unsafe -> ObjectStreamClass -> ObjectInputStream の順番で使えるものを使ってる感じ。
でも今何のオプションも入れていないJava17環境で動いてるので、 どれかは動いている。
でも、どれもjavaパッケージでsetAccessible(true)を使っているのに使えてるのなんで？
(Gson自体がJava8コンパイルだから？でもそれだったらAopProxyも同じはずでも落ちてる)

**Comment by jflute** [comment]
そもそも、AopProxyにて defineClass() を何のために使っているか？まとめよう。
staticイニシャライザーで落ちてるってことはアプリでやりたいこと関係なく問答無用ってことなので、
もしかしたら回避できるパスがあったりしないだろうか？

何にせよ、Unsafeでの代替とかのために現状をもっと細かく把握する必要がありそう。

**Comment by jflute** [comment]
AbstractGeneratorのstaticイニシャライザーでは、defineClass()をsetAccessible(true)してdefineClass()のリフレクション参照をdefineClassMethodとして保持している。
このsetAccessible(true)でアクセス例外になってしまうのだが、そもそもこれを誰がどう使っているのか？
```
static {
    protectionDomain = (ProtectionDomain) AccessController.doPrivileged(new PrivilegedAction<Object>() {
        public Object run() {
            return AspectWeaver.class.getProtectionDomain();
        }
    });

    AccessController.doPrivileged(new PrivilegedAction<Object>() {
        public Object run() {
            final Class<?>[] paramTypes = new Class[] { String.class, byte[].class, int.class, int.class, ProtectionDomain.class };
            try {
                final Class<?> loader = LdiClassUtil.forName(ClassLoader.class.getName());
                defineClassMethod = loader.getDeclaredMethod(DEFINE_CLASS_METHOD_NAME, paramTypes);
                defineClassMethod.setAccessible(true);
            } catch (final NoSuchMethodException e) {
                throw new NoSuchMethodRuntimeException(ClassLoader.class, DEFINE_CLASS_METHOD_NAME, paramTypes, e);
            }
            return null;
        }
    });
}
```

AbstractGeneratorのtoClass()が利用している。
JavassistのCtClassからbytecodeを作って、引数で指定されたClassLoaderにdefineするようにしている。
(ctClassはエンハンスされたクラスが来ることが想定される)
```
public Class<?> toClass(final ClassLoader classLoader, final CtClass ctClass) {
    try {
        final byte[] bytecode = ctClass.toBytecode();
        return (Class<?>) defineClassMethod.invoke(classLoader,
                new Object[] { ctClass.getName(), bytecode, new Integer(0), new Integer(bytecode.length), protectionDomain });
    } catch (final CannotCompileException e) {
        throw new CannotCompileRuntimeException(e);
    } catch (final IOException e) {
        throw new IORuntimeException(e);
    } catch (final IllegalAccessException e) {
        throw new IllegalAccessRuntimeException(ClassLoader.class, e);
    } catch (final InvocationTargetException e) {
        throw new InvocationTargetRuntimeException(ClassLoader.class, e);
    }
}
```

ClassLoaderを指定できるようにしているのは、たぶんホットデプロイ環境でホットデプロイのClassLoaderに登録させるようにするためではないだろうか？
(もしその都合がなければ、defineしなくても良かったりしないだろうか？)

toClass()の呼び出し元の一つはEnhancedClassGenerator、その元はAspectWeaver。
エンハンス前のクラスのClassLoaderを指定しているのでやはり同じClassLoaderになるようにしているっぽい。
```
// EnhancedClassGenerator
public Class<?> toClass(final ClassLoader classLoader) {
    final Class<?> clazz = toClass(classLoader, enhancedClass);
    enhancedClass.detach();
    enhancedClass = null;
    return clazz;
}

// AspectWeaver
public Class<?> generateClass() {
    if (enhancedClass == null) {
        enhancedClass = enhancedClassGenerator.toClass(LdiClassLoaderUtil.getClassLoader(targetClass));

        for (int i = 0; i < methodInvocationClassList.size(); ++i) {
            final Class<?> methodInvocationClass = (Class<?>) methodInvocationClassList.get(i);
            setStaticField(methodInvocationClass, "targetClass", targetClass);
        }
    }

    return enhancedClass;
}
```

もう一個のtoClass()の呼び出し元はMethodInvocationClassGenerator、、その元はAspectWeaver。
まあ、仕組み上のやってることはあまり変わらないっぽい。
```
// MethodInvocationClassGenerator
public Class<?> toClass(final ClassLoader classLoader) {
    final Class<?> clazz = toClass(classLoader, methodInvocationClass);
    methodInvocationClass.detach();
    methodInvocationClass = null;
    return clazz;
}


// AspectWeaver
public void setInterceptors(final Method method, final MethodInterceptor[] interceptors) {
    final String methodInvocationClassName = getMethodInvocationClassName(method);
    final MethodInvocationClassGenerator methodInvocationGenerator =
            new MethodInvocationClassGenerator(classPool, methodInvocationClassName, enhancedClassName);

    final String invokeSuperMethodName = createInvokeSuperMethod(method);
    methodInvocationGenerator.createProceedMethod(method, invokeSuperMethodName);
    enhancedClassGenerator.createTargetMethod(method, methodInvocationClassName);

    final Class<?> methodInvocationClass = methodInvocationGenerator.toClass(LdiClassLoaderUtil.getClassLoader(targetClass));
    setStaticField(methodInvocationClass, "method", method);
    setStaticField(methodInvocationClass, "interceptors", interceptors);
    setStaticField(methodInvocationClass, "parameters", parameters);
    methodInvocationClassList.add(methodInvocationClass);
}
```

**Comment by jflute** [comment]
UnsafeのdefineClass()を使えば代替できる的な記事があったけど...
https://qiita.com/Tsuyoshi_Murakami/items/07c967cc651ad2eb1113


OpenJDKのソースコードを見ると、2018年に完全に消えてる。
(つまり、Java10以降で消えたんじゃないかなと)

// 8193033: remove terminally deprecated sun.misc.Unsafe.defineClass 
https://github.com/openjdk/jdk/commit/cfb102ab895e503d96ee273eb920f054bb861840

もう、ClassLoaderを指定してエンハンスするってのはできなくなったと言えないだろうか？

他のフレームワークではどうしてるんだろう？と思ったけど、これはホットデプロイ機能と絡む話なので、他では関係ないのかもしれない。(defineClassせずにClassLoader気にせずエンハンスしてる？)

つまり、ホットデプロイを捨てれば大丈夫だったりするだろうか？

**Comment by jflute** [comment]
ClassLoaderのdefineClass()はprotectedなので、継承したクラスで入口を作ってあげたら呼べないだろうか？
もちろん自前ClassLoader限定になるが「自前ClassLoaderに突っ込むことさえできれば良い？」のであれば、それでいけないだろうか？

環境を作ってtrial and errorするしかないか。

**Comment by jflute** [comment]
試しに、--illegal-access=permit; をVM引数で指定したらどうなるか？ってやってみたら...

```
--illegal-access=permit; support was removed in 17.0
```

削除されたようだ。実際に実行してみて発生する例外が変わらない。

// JDK 17の内部JDK要素の強力なカプセル化 
https://www.infoq.com/jp/news/2021/07/internals-encapsulated-jdk17/

ちゃんと、--add-opensで細かく指定しろってことなのかな。

**Comment by jflute** [comment]
VM引数にadd-opensオプションを追加したらAOP動作した。
```
--add-opens java.base/java.lang=ALL-UNNAMED
```

うーむー、AOPはオプション前提の機能にするってのも一つの選択肢かも。

**Comment by jflute** [comment]
Javassistは何か対策してないだろうか？と思って見てみたら、Javassistもだいぶ苦戦しているような感じだった。
CtClassのtoClass()を見てみると、できるだけ頑張ってdefineClassするけど、最終的にダメなら例外と。

試しに、Lasta Diの方でダメだった場合にCtClassのtoClass()に任せるようにしたら同じようにダメだった。

```
// defineClass() headache
Pointcut pointcut = new PointcutImpl(new String[] { "mystic" });
Aspect aspect = new AspectImpl(new SeaMethodInterceptor(), pointcut);
AopProxy aopProxy = new AopProxy(getClass(), new Aspect[] { aspect });
log(aopProxy);
```

```
2024-06-17 23:51:59,013 [main] DEBUG (PlainTestCase@log():748) - Failed to finish the test: DemoTest.test_demo()
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2f96847e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:159)
	at javassist.util.proxy.DefineClassHelper$JavaOther.defineClass(DefineClassHelper.java:213)
	at javassist.util.proxy.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:52)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
	at javassist.ClassPool.toClass(ClassPool.java:1240)
	at javassist.ClassPool.toClass(ClassPool.java:1098)
	at javassist.ClassPool.toClass(ClassPool.java:1056)
	at javassist.CtClass.toClass(CtClass.java:1298)
	at org.lastaflute.di.core.aop.javassist.AbstractGenerator.toClass(AbstractGenerator.java:175)
	at org.lastaflute.di.core.aop.javassist.EnhancedClassGenerator.toClass(EnhancedClassGenerator.java:63)
	at org.lastaflute.di.core.aop.javassist.AspectWeaver.generateClass(AspectWeaver.java:94)
	at org.lastaflute.di.core.aop.proxy.AopProxy.<init>(AopProxy.java:74)
	at org.lastaflute.di.core.aop.proxy.AopProxy.<init>(AopProxy.java:52)
	at org.docksidestage.unit.DemoTest.test_demo(DemoTest.java:58)
...
```

これはやはり、AOPはオプション前提の機能にならざるを得ないだろうか？

**Comment by jflute** [comment]
HotdeployClassLoaderで、defineClass()をpublicにするファサードメソッドを作ったら(hotなら)動いた。
```
// HotdeployClassLoader
@Override
public Class<?> invokeDefineClass(String name, byte[] bytecode, int off, int len, ProtectionDomain protectionDomain) {
    return defineClass(name, bytecode, off, len, protectionDomain);
}
```

でも当然、coolだと動かない。coolは起動時に落ちる。(Logicクラスとか全部評価されるので)
hotだけ動いても意味ないし、なまじローカルでは動いてデプロイすると動かないってのが良くない。

でも、coolでもClassLoaderを自前のものに差し替えて実行するような仕組みを作れば動くが...
ちょっとそこまでやるかは微妙。大丈夫だと思うが副作用が不安。(費用対効果が悪い？)

まあアプリでClassLoaderを自前で用意してやるってのはアリなので、その拡張ポイントは用意しておくか？
ちょうど今EnhancedClassDefineableインターフェースを仮作成しているが、その方式を正式に？
(coolの拡張は単に各所でThreadのcontextClassLoaderを設定してもらえば良いが、HotdeployBehaviorの拡張ってどう演出しよう？)

ただAOPはオプション前提の機能とするのであればその拡張ポイントは不要ではある。
でもいざってときのために拡張できるに越したことはないのでやっておくか。

**Comment by jflute** [comment]
Springのコードを参考にさせてもらったら、MethodHandlesというクラスの存在を知った。
```
MethodHandles.Lookup lookup = MethodHandles.privateLookupIn(targetClass, MethodHandles.lookup());
return lookup.defineClass(bytecode);
```

これ...defineできちゃうのか？
MethodHandles自体はjava8で存在するけどdefineClass()はjava9からなので、
利用するにはjava8版ではリフレクションになるけど。

**Comment by jflute** [comment]
MethodHandles, エンハンス元クラスとエンハンス先クラスのパッケージ同じじゃないといけないことが判明。
普通のエンハンスは問題ないけど、MethodInvocationのエンハンスが見事にヒット。
MethodInvocationのエンハンス先クラスのパッケージを変更する修正を入れたらOKだった。

ローカル環境では、MethodHandles方式でJava17で動いている。
どんなダメなときがあるのか？がまだわからないのでテストが必要。

それにしても、MethodHandlesはJavassistも使っているようなので、Javassistを使えばいい？
(一度、試した時にダメだったような気がするんだけど、もっかい試してみる？)

**Comment by jflute** [comment]
Javassistで試してダメだったのは...
https://github.com/lastaflute/lastaflute/issues/83#issuecomment-2173640294

CtClass@toClass()だと、"Class<?> neighbor" が null で指定されてMethodHandlesに到達しない。
neighborはエンハンス元クラス、MethodHandlesのLookupで必要になる。
CtClassはエンハンス元クラスを持ってないので引数で指定する必要があるようだ。

Lasta DiでもMethodInvocationの方が元クラスを持ってなかったので直したくらいなのでそういうことか。

どうしようかな、Lasta Diオリジナルでダメだった場合は最後Javassistにまかせてみようかな。

**Comment by jflute** [comment]
> どうしようかな、Lasta Di自前でダメだった場合は最後Javassistにまかせてみようかな。

基本的にはやってること同じなので、まあいいか。
またJDKで変化があったときに追従してくれるという面はあるが...
Lasta Diをしっかり成長させた方が良いかもなので、そこはつど変化対応
頭の片隅に入れておいて、Lasta Diでダメだった場合に検討する。
```
// #for_now jflute quit finally javassist to verify Lasta Di logic (2024/06/19)
//// finally, ask javassist (for future change)
//try {
//    enhancedClass = invokeCtClassToClass(ctClass);
//} catch (Throwable cause) {
//    currentCauseList.add(cause);
//}
```

**Comment by jflute** [comment]
CoolDeployやWarmDeploy(UnitTest)では動くようになったけど、Hotdeployだと動かない。
```
java.lang.NoClassDefFoundError: org/docksidestage/app/logic/DanceSongLogic$$EnhancedByLastaDi$$2f1a1c82
	at org.lastaflute.di.core.aop.javassist.OrgDocksidestageAppLogicDanceSongLogic$$EnhancedByLastaDi$$2f1a1c82$$MethodInvocation$$letsDance$$0.proceed(MethodInvocationClassGenerator.java)
	at org.lastaflute.di.tx.DefaultTransactionCallback.execute(DefaultTransactionCallback.java:37)
	at org.lastaflute.di.tx.adapter.JTATransactionManagerAdapter.requiresNew(JTATransactionManagerAdapter.java:73)
	at org.lastaflute.di.tx.RequiresNewTxInterceptor.invoke(RequiresNewTxInterceptor.java:29)
	at org.lastaflute.di.core.aop.javassist.OrgDocksidestageAppLogicDanceSongLogic$$EnhancedByLastaDi$$2f1a1c82$$MethodInvocation$$letsDance$$0.proceed(MethodInvocationClassGenerator.java)
	at org.docksidestage.app.logic.DanceSongLogic$$EnhancedByLastaDi$$2f1a1c82.letsDance(DanceSongLogic$$EnhancedByLastaDi$$2f1a1c82.java)
	at org.docksidestage.app.web.product.ProductListAction.index(ProductListAction.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
Caused by: java.lang.ClassNotFoundException: org.docksidestage.app.logic.DanceSongLogic$$EnhancedByLastaDi$$4d6f9910
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```

ClassLoader違いだろうか？

ModuleHandles.Lookupは、lookupClassのClassLoaderにdefineしているように見える。
lookupClassって、targetClassだからHotdeployClassLoaderな気がする。

スタックトレースを見ると、システムのClassLoaderを探しに行ってる？
でも省略されちゃってるからなんとも言えないか？

ちょっと現象の詳細はもうちょい分析する必要がある。

一方で、前にHotdeployClassLoaderでインターフェース経由でdefineしたら動いた。
でも、coolのときdefine方法が変わるってのはなんとも怖い感じもする。

**Comment by jflute** [comment]
> スタックトレースを見ると、システムのClassLoaderを探しに行ってる？
> でも省略されちゃってるからなんとも言えないか？

あっ、MethodInvocationはLookupクラスがフレームワーク内のクラスでHotdeployにはならないので、
それでエンハンスされたクラスもシステムClassLoaderに読まれるから、
MethodInvocationから見るとHotdeployのDanceSongLogicの見つからないってことなのかも。

うーむー、これなかなか回避しようがないかも...
やはり、Hotdeploy限定のインターフェース経由でdefineするしかないかなー。

**Comment by jflute** [comment]
> やはり、Hotdeploy限定のインターフェース経由でdefineするしかないかなー。

MethodInvocationだけHotdeployのときはインターフェース経由でdefineするようにしてみた。
そうすることで動いた。

メインコンポーネントはhotでもcoolでもMethodHandlesになるので、
何かMethodHandlesで環境問題があればそっちで発生するだろうと。

**Comment by jflute** [comment]
ということで、Lasta Diを修正している。

https://github.com/lastaflute/lasta-di/issues/37
